// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForCreateEvent implements pgx.CopyFromSource.
type iteratorForCreateEvent struct {
	rows                 []CreateEventParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateEvent) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateEvent) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].EventTimestamp,
		r.rows[0].TopicName,
		r.rows[0].TopicOffset,
		r.rows[0].TopicPartition,
		r.rows[0].EventHeaders,
		r.rows[0].EventKey,
		r.rows[0].EventValue,
	}, nil
}

func (r iteratorForCreateEvent) Err() error {
	return nil
}

func (q *Queries) CreateEvent(ctx context.Context, arg []CreateEventParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"events"}, []string{"event_timestamp", "topic_name", "topic_offset", "topic_partition", "event_headers", "event_key", "event_value"}, &iteratorForCreateEvent{rows: arg})
}
