// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID             int32
	InsertedAt     pgtype.Timestamptz
	EventTimestamp pgtype.Timestamp
	TopicName      string
	TopicOffset    int64
	TopicPartition int32
	EventHeaders   []byte
	EventKey       []byte
	EventValue     []byte
}
