// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID                int32
	InsertedAt        pgtype.Timestamptz
	EventhubTimestamp pgtype.Timestamptz
	EventTimestamp    pgtype.Timestamptz
	SchemaID          pgtype.Int4
	SchemaFormat      string
	TopicName         string
	TopicOffset       int64
	TopicPartition    int32
	EventType         string
	EventHeaders      []byte
	EventKey          []byte
	EventValue        []byte
	LastIndexedAt     pgtype.Timestamptz
}

type EventIndexConfig struct {
	ID          int32
	InsertedAt  pgtype.Timestamptz
	EventType   string
	KeySelector []string
	IndexColumn string
}

type TimestampConfig struct {
	ID          int32
	InsertedAt  pgtype.Timestamptz
	EventType   string
	KeySelector []string
}
